language: perl
perl:
  - "5.16"
    - "5.14"
	  - "5.12"
	    - "5.10"
		  - "5.8"
install: "make test-deps"
script: "make test"
notifications:
  email:
    - hidetomo.watanabe@dena.com
  use_notice: true
