language: perl
perl:
  - "5.12"
install:
  - "cpanm --installdeps --notest . || cat ~/.cpanm/build.log"
after_failure:
  - "cat ~/.cpanm/build.log"
script: "make test"
notifications:
  email:
    - hidetomo.watanabe@dena.com
  use_notice: true
